const ACTION_TYPES = {
    GET_USER_WALLET_SUCCESS: 'GET_USER_WALLET_SUCCESS',
    CURRENCY_INPUT_CHANGE: 'CURRENCY_INPUT_CHANGE',
    CURRENCY_SELECT_CHANGE: 'CURRENCY_SELECT_CHANGE',
    FETCH_RATES_SUCCESS: 'FETCH_RATES_SUCCESS',
    EXCHANGE: 'EXCHANGE',
    TOGGLE_EXCHANGE_SUCCESS_MODAL: 'TOGGLE_EXCHANGE_SUCCESS_MODAL'
}

export default ACTION_TYPES;